### ISSUE TITLE
Remapping media keys to Spotify ?

### ISSUE THREAD

**Issue by Trosterud** [sam-hosseini/dotfiles#3]
Have you found any fixes to do this? Best I've tried so far is just disabling iTunes with this config. But it also disables the button for spotfity

Wouldn't it be nice to start Spotify with f8?

```
    # Stop iTunes from responding to the keyboard media keys
    launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist 2> /dev/null
```

**Comment by sam-hosseini** [comment]
> Wouldn't it be nice to start Spotify with f8?

Would be nice for sure 👍

I remember when macOS High Sierra caused F7-F9 to stop working for Spotify, I added `highsierramediakeyenabler` in my global packages f1e5d9782d1359332b92c4437dfd42c5198cceb6

But then when Mojave came and I upgraded, the keys worked "correctly" again, and I removed it 72b8e49f62b1f2302ce90f10b4d6290e504baa77

So I no longer can reproduce the issue neither in Mojave nor in Catalina 🤔
