### ISSUE TITLE
Fish functions don't autocomplete git branch names

### ISSUE THREAD

**Issue by Trosterud** [sam-hosseini/dotfiles#4]
Solution (if you want to implement) is to use abbreviations instead of function for certain tasks

You can see my [dotfiles](https://github.com/Trosterud/dotfiles/commit/97821e273d6076f6b2379e07987bac1d6c1a5aa0)  for how to do it, but basically for myself I solved it with:

-  adding a file /fish/abbreviations.fish. Syntax is like this per line:
abbr -a gco git checkout

- adding the following line to /fish/config.fish
source ~/.config/fish/abbreviations.fish

- adding the following symlink to bootstrap.sh
    symlink "fish:abbreviations.fish" ${DOTFILES_REPO}/fish/abbreviations.fish ~/.config/fish/abbreviations.fish

Just wanted to give back, as I've learned so much from your dotfiles and article! And had so much pleasure from the implemention of similar principles  and methods on my end 😄

**Comment by Trosterud** [comment]
If you really want to get the same functionality with function, here is a syntax that might be able to do it:
Use --wraps argument to function and complete, which enables completion inheritance. function foo --wraps=bar gives foo all completions registered for bar.

https://superuser.com/questions/846310/how-can-i-enable-tab-completion-for-a-fish-function-alias

**Comment by sam-hosseini** [comment]
@Trosterud that's great I didn't know that! I implemented it in 0e54eb8 and now my `gp` and `gl` and `lo` are better and I don't have to rely on command history, completion itself works 👍🏼

> Just wanted to give back, as I've learned so much from your dotfiles and article! And had so much pleasure from the implemention of similar principles and methods on my end 😄

Makes my day to hear it 😊 you're welcome 🙌🏼
